Set default engineVersion to be consistent with documentation
jenkinsci/hashicorp-vault-plugin pull request #121
Opened 2020-08-19 18:02 UTC by aajimal

Documentation (as well as when creating from the UI) suggests a default engine version is `2`. When this is not explicitly set we can get a stacktrace similar to: 

`2020-08-18 05:51:42.583+0000 [id=266470] INFO c.d.j.v.c.c.VaultHelper$SecretRetrieve#call: Retrieving vault secret path=secret/ci/global key=bitbucket_user engineVersion=null 2020-08-18 05:51:42.584+0000 [id=266470] INFO c.d.j.v.c.common.VaultHelper#retrieveVaultCredentials: Retrieving vault credential ID : global_vault_cicd 2020-08-18 05:51:42.584+0000 [id=266470] INFO com.bettercloud.vault.Vault#<init>: Constructing a Vault instance with no provided Engine version, defaulting to version 2. 2020-08-18 05:51:42.655+0000 [id=266470] WARNING o.e.j.s.h.ContextHandler$Context#log: Error while serving https://removed-for-security/job/myjob/descriptorByName/com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource/fillRepositoryItems java.lang.NullPointerException at com.bettercloud.vault.api.Logical.read(Logical.java:75) at com.datapipe.jenkins.vault.VaultAccessor.read(VaultAccessor.java:90) at com.datapipe.jenkins.vault.credentials.common.VaultHelper$SecretRetrieve.call(VaultHelper.java:121) Caused: java.lang.RuntimeException at com.datapipe.jenkins.vault.credentials.common.VaultHelper$SecretRetrieve.call(VaultHelper.java:132) at com.datapipe.jenkins.vault.credentials.common.VaultHelper.getVaultSecret(VaultHelper.java:44) at com.datapipe.jenkins.vault.credentials.common.VaultUsernamePasswordCredentialImpl.getUsername(VaultUsernamePasswordCredentialImpl.java:89) at com.cloudbees.jenkins.plugins.bitbucket.api.credentials.BitbucketUsernamePasswordAuthenticator.<init>(BitbucketUsernamePasswordAuthenticator.java:58) at com.cloudbees.jenkins.plugins.bitbucket.api.credentials.BitbucketUsernamePasswordAuthenticatorSource.convert(BitbucketUsernamePasswordAuthenticatorSource.java:54) at com.cloudbees.jenkins.plugins.bitbucket.api.credentials.BitbucketUsernamePasswordAuthenticatorSource.convert(BitbucketUsernamePasswordAuthenticatorSource.java:36) at jenkins.authentication.tokens.api.AuthenticationTokens.convert(AuthenticationTokens.java:148) at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource$DescriptorImpl.doFillRepositoryItems(BitbucketSCMSource.java:1209) at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396) Caused: java.lang.reflect.InvocationTargetException at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:400) at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408) at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)`

This situation is remedied by:
- Setting `engineVersion`
- Creating the credential via UI
- Editing engineVersion from the UI and saving to persist the change. 

Of course a user can explicitly call `setEngineVersion(2)` when creating credentials. However, documentation and behavior when creating through the UI suggests that `2` is the default value if nothing is provided. Therefore perhaps it should explicitly be set in accordance with the docs.

2020-08-19 19:21 UTC, jetersen requested changes
That's not how it's suppose to be used.

If anything this need to be set during `readResolve` to fix it for those upgrading.

2020-08-20 04:01 UTC, aajimal commented
It looks like `readResolve` is already doing such a check?

`protected Object readResolve() {
        if (configuration != null && configuration.getEngineVersion() == null) {
            configuration.setEngineVersion(DescriptorImpl.DEFAULT_ENGINE_VERSION);
        }
        return this;
    }
`

2020-08-20 05:48 UTC, jetersen commented
Right... Now I get it...

These 3 classes uses `getVaultSecret` in `VaultHelper` and are not using the `VaultBuildWrapper` way of getting secrets.

In `VaultBuildWrapper` we have this piece of code that fixes the config before getting the vault secrets:
https://github.com/jenkinsci/hashicorp-vault-plugin/blob/eed39e30f830a5313eb08288f39bceb435578445/src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java#L241-L262

However in `VaultHelper` there is no fixing the defaults.

I remember trying my hand at rewriting the whole thing at some point but got scrapped due to lack of effort on my part.

2020-08-20 06:30 UTC, jetersen commented
Okay not sure why the bindings are not passing the build that would make stuff so much easier 😓

2020-08-21 00:52 UTC, aajimal commented
Is the VaultBuildWrapper() intended for use within an actual build execution?
The error I was getting was being triggered even before this -- specifically when trying to configure the SCM source for the pipeline itself. 

It seems that this may be caused by `SecretRetreive` and perhaps could be addressed by setting the default value here where the configuration is created:

https://github.com/jenkinsci/hashicorp-vault-plugin/blob/eed39e30f830a5313eb08288f39bceb435578445/src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultHelper.java#L103

Just below that is when then exception seems to be thrown on the read request.

2020-08-21 01:49 UTC, aajimal commented
Also as an example, the bitbucket-branch-source code which is probably pulling the credential looks to be doing something like this: 

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketUsernamePasswordAuthenticator.java#L56-L60

2020-08-21 05:10 UTC, jetersen commented
The idea is they should default the vault engine version to what is set globally or on a folder or job specifically on the Vault configuration side.

These credential than have the option also to set the engine version and the default there is `null` as a way to signal that it should default to a config from above.
So the fact that `VaultHelper` only has access to `GlobalConfiguration` and lacks job/folder context is somewhat a misstep.

I have a commit locally that will align it closer to default to it, yet still haven't fixed the lack of build context.

2020-08-26 09:33 UTC, closed without merging