Add secret file credential type
jenkinsci/hashicorp-vault-plugin pull request #178
Opened 2021-05-04 14:36 UTC by jamesrobson-secondmind

This adds the ability to create secret file credentials (equivalent to [org.jenkinsci.plugins.plaincredentials.FileCredentials](https://github.com/jenkinsci/plain-credentials-plugin/blob/master/src/main/java/org/jenkinsci/plugins/plaincredentials/FileCredentials.java)). The contents of the file can either be taken from a single key within a secret, or contain the whole secret as json.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-09-06 16:00 UTC, jetersen requested changes

2021-09-06 16:00 UTC, jetersen commented on pom.xml
> +    </dependency>
I don't like this direct dependencies.

JSONObject from jenkins already exist: https://github.com/jenkinsci/json-lib/blob/16052d1f74908fb59430eddd73f42aec2469b313/src/main/jdk15/net/sf/json/JSONObject.java#L125 with a toString method

The com.bettercloud.vault-java-driver already comes with a JSON parser.

You could also depend on https://github.com/jenkinsci/jackson2-api-plugin

2021-09-07 16:17 UTC, jetersen commented on src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultFileCredentialImpl.java
> +            content = new JSONObject().fromObject(s).toString();
A static method exist, no need to call new :) https://github.com/jenkinsci/json-lib/blob/16052d1f74908fb59430eddd73f42aec2469b313/src/main/jdk15/net/sf/json/JSONObject.java#L138-L140
```suggestion
            content = JSONObject.fromObject(s).toString();
```

2021-10-01 16:06 UTC, jamesrobson-secondmind commented
The requested changes have been made and the tests are now passing, so can this be approved?

2021-10-01 16:15 UTC, jetersen approved these changes

2021-10-01 16:24 UTC, merged

2021-10-01 16:25 UTC, jetersen commented
@jamesrobson-secondmind thanks for your contribution :)